### ISSUE TITLE
UnauthorizedError: jwt malformed

### ISSUE THREAD

**Issue by AntonAL** [growthbook/growthbook-proxy#59]
Following [official documentation](https://docs.growthbook.io/self-host/proxy), I've set up a GrowthBook Proxy and got following error:

```
ERROR (UnauthorizedError/59 on server.my-features-service): ERROR /api/v1/sdk-connections?withProxy=1&limit=100&offset=0
    UnauthorizedError: jwt malformed
        at /usr/local/src/app/node_modules/express-jwt/lib/index.js:105:22
        at Object.module.exports [as verify] (/usr/local/src/app/node_modules/jsonwebtoken/verify.js:63:12)
        at verifyToken (/usr/local/src/app/node_modules/express-jwt/lib/index.js:103:13)
        at nextTask (/usr/local/src/app/node_modules/async/dist/async.js:5789:27)
        at next (/usr/local/src/app/node_modules/async/dist/async.js:5797:13)
        at /usr/local/src/app/node_modules/async/dist/async.js:327:20
        at /usr/local/src/app/node_modules/express-jwt/lib/index.js:15:12
        at getSecret (/usr/local/src/app/node_modules/express-jwt/lib/index.js:99:11)
        at nextTask (/usr/local/src/app/node_modules/async/dist/async.js:5789:27)
        at Object.waterfall (/usr/local/src/app/node_modules/async/dist/async.js:5800:9)
        at Object.awaitable [as waterfall] (/usr/local/src/app/node_modules/async/dist/async.js:211:32)
        at middleware (/usr/local/src/app/node_modules/express-jwt/lib/index.js:93:11)
        at middleware (/usr/local/src/app/packages/back-end/dist/services/auth/LocalAuthConnection.js:78:9)
        at Layer.handle [as handle_request] (/usr/local/src/app/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/usr/local/src/app/node_modules/express/lib/router/index.js:328:13)
        at /usr/local/src/app/node_modules/express/lib/router/index.js:286:9
        at Function.process_params (/usr/local/src/app/node_modules/express/lib/router/index.js:346:12)
        at next (/usr/local/src/app/node_modules/express/lib/router/index.js:280:10)
        at cors (/usr/local/src/app/node_modules/cors/lib/index.js:188:7)
        at /usr/local/src/app/node_modules/cors/lib/index.js:224:17
        at originCallback (/usr/local/src/app/node_modules/cors/lib/index.js:214:15)
        at /usr/local/src/app/node_modules/cors/lib/index.js:219:13
{"level":50,"time":1719311872231,"pid":48,"hostname":"proxy.my-features-service","msg":"connection polling error: status code is 401"}
```

It seems like the GrowthBook Proxy is trying to poll main GrowthBook API instance and fails because of JWT.
But, I could not find a way of how to setup it for GrowthBook Proxy.

My compose.yml is following:

```yml
  proxy:
    image: 'growthbook/proxy:latest'
    container_name: ${COMPOSE_PROJECT_NAME}-proxy
    hostname: ${FEATURES_PROXY_HOSTNAME}
    ports:
      - ${FEATURES_PROXY_PORT}
    environment:
      - GROWTHBOOK_API_HOST=http://${FEATURES_SERVER_HOSTNAME}:${FEATURES_SERVER_API_PORT}
      - SECRET_API_KEY=${FEATURES_SERVER_SECRET_API_KEY}
    healthcheck:
      test: ['CMD', 'bash', '-c', "echo -n '' > /dev/tcp/127.0.0.1/${FEATURES_PROXY_PORT}"]
      interval: 5s
    depends_on:
      server:
        condition: service_healthy
        restart: true
    networks:
      - ${NETWORK_NAME}
  server:
    image: 'growthbook/growthbook:latest'
    container_name: ${COMPOSE_PROJECT_NAME}-server
    hostname: ${FEATURES_SERVER_HOSTNAME}
    ports:
      - ${FEATURES_SERVER_ADMIN_PORT}
      - ${FEATURES_SERVER_API_PORT}
    healthcheck:
      test: ['CMD', 'bash', '-c', "echo -n '' > /dev/tcp/127.0.0.1/${FEATURES_SERVER_API_PORT}"]
      interval: 5s
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - MONGODB_URI=${FEATURES_DB_URI}
      - APP_ORIGIN=https://${INGRESS_HOSTNAME}:${INGRESS_FEATURES_ADMIN_PORT}
      - API_HOST=https://${INGRESS_HOSTNAME}:${INGRESS_FEATURES_API_PORT}
      - JWT_SECRET=${FEATURES_SERVER_JWT_SECRET}
      - ENCRYPTION_KEY=${FEATURES_SERVER_ENCRYPTION_KEY}
      - PROXY_ENABLED=1
      - PROXY_HOST_INTERNAL=http://${FEATURES_PROXY_HOSTNAME}:${FEATURES_PROXY_PORT}
      - PROXY_HOST_PUBLIC=https://${INGRESS_HOSTNAME}:${INGRESS_FEATURES_PROXY_PORT}
      - SECRET_API_KEY=${FEATURES_SERVER_SECRET_API_KEY}
    volumes:
      - ./data/growthbook/uploads:/usr/local/src/app/packages/back-end/uploads
    networks:
      - ${NETWORK_NAME}
```

.env file

```
# Ingress
#
INGRESS_HOSTNAME=local.my-features-service

INGRESS_FEATURES_ADMIN_PORT=4000
INGRESS_FEATURES_API_PORT=4001
INGRESS_FEATURES_PROXY_PORT=4300


# Internal networking
#
NETWORK_NAME=my-features-service

FEATURES_SERVER_HOSTNAME=server.$NETWORK_NAME
# Required ports in https://docs.growthbook.io/self-host#installation
FEATURES_SERVER_ADMIN_PORT=3000
FEATURES_SERVER_API_PORT=3100
FEATURES_SERVER_JWT_SECRET=example-jwt-secret
FEATURES_SERVER_ENCRYPTION_KEY=example-encryption-key
# Used for connecting "proxy" to "server"
FEATURES_SERVER_SECRET_API_KEY=example-secret-api-key

FEATURES_PROXY_HOSTNAME=proxy.$NETWORK_NAME
FEATURES_PROXY_PORT=3300

FEATURES_DB_HOSTNAME=db.$NETWORK_NAME
FEATURES_DB_ROOT_USERNAME=root
FEATURES_DB_ROOT_PASSWORD=password
FEATURES_DB_URI=mongodb://$FEATURES_DB_ROOT_USERNAME:$FEATURES_DB_ROOT_PASSWORD@$FEATURES_DB_HOSTNAME:27017/growthbook?authSource=admin
```

GrowthBook is deployed under custom domain, so, I have an "ingress" service, based on Nginx, which handles SSL and upstream stuff for external clients, like GrowthBook admin and front-end  (`APP_ORIGIN`, `API_HOST` are for that).

```
server {
  server_name ${INGRESS_HOSTNAME};

  listen ${INGRESS_FEATURES_ADMIN_PORT} ssl;
  listen [::]:${INGRESS_FEATURES_ADMIN_PORT} ssl;

  http2 on;

  auth_basic 'Admin area';
  auth_basic_user_file /etc/nginx/auth/.htpasswd;

  ssl_certificate /etc/nginx/certs/${INGRESS_HOSTNAME}/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/${INGRESS_HOSTNAME}/privkey.pem;

  location / {
    proxy_pass http://${FEATURES_SERVER_HOSTNAME}:${FEATURES_SERVER_ADMIN_PORT};
  }
}

# Used by GrowthBook Admin
server {
  server_name ${INGRESS_HOSTNAME};

  listen ${INGRESS_FEATURES_API_PORT} ssl;
  listen [::]:${INGRESS_FEATURES_API_PORT} ssl;

  http2 on;

  # NOTE: HTTP Basic authorization should not be presented here, because it causes problems with CORS

  ssl_certificate /etc/nginx/certs/${INGRESS_HOSTNAME}/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/${INGRESS_HOSTNAME}/privkey.pem;

  location / {
    proxy_pass http://${FEATURES_SERVER_HOSTNAME}:${FEATURES_SERVER_API_PORT};
  }
}

# Will be used by clients, outside of Docker Compose network, like "desk" app
# The GrowthBook Proxy server sits between your application and GrowthBook (both Cloud or Self-hosted instances).
# It turbocharges your GrowthBook implementation by providing speed, scalability, security, and real-time feature rollouts.
# https://docs.growthbook.io/self-host/proxy
server {
  server_name ${INGRESS_HOSTNAME};

  listen ${INGRESS_FEATURES_PROXY_PORT} ssl;
  listen [::]:${INGRESS_FEATURES_PROXY_PORT} ssl;

  http2 on;

  # NOTE: HTTP Basic authorization should not be presented here, because it causes problems with CORS

  ssl_certificate /etc/nginx/certs/${INGRESS_HOSTNAME}/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/${INGRESS_HOSTNAME}/privkey.pem;

  location / {
    proxy_pass http://${FEATURES_PROXY_HOSTNAME}:${FEATURES_PROXY_PORT};
  }
}
```

Currently, the problem arise in server-side Node.js app, which is located in internal network of Docker Compose and sends requests to "proxy" service directly (not through ingress).
